#include "ui.h"

UI::UI()
{

}
void UI::setupUi(QMainWindow *MainWindow)
{
    if (MainWindow->objectName().isEmpty())
        MainWindow->setObjectName(QStringLiteral("MainWindow"));
    MainWindow->resize(897, 684);
    this->centralWidget = new QWidget(MainWindow);
    this->centralWidget->setObjectName(QStringLiteral("centralWidget"));
    linear1 = new QPushButton(centralWidget);
    buttonGroup1 = new QButtonGroup(MainWindow);
    buttonGroup1->setObjectName(QStringLiteral("buttonGroup1"));
    buttonGroup1->addButton(linear1);
    linear1->setObjectName(QStringLiteral("linear1"));
    linear1->setGeometry(QRect(50, 110, 31, 31));
    linear1->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/1a.png);"));
    linear1_2 = new QPushButton(centralWidget);
    buttonGroup1->addButton(linear1_2);
    linear1_2->setObjectName(QStringLiteral("linear1_2"));
    linear1_2->setGeometry(QRect(50, 140, 31, 31));
    linear1_2->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/2a.png);"));
    linear1_3 = new QPushButton(centralWidget);
    buttonGroup1->addButton(linear1_3);
    linear1_3->setObjectName(QStringLiteral("linear1_3"));
    linear1_3->setGeometry(QRect(50, 200, 31, 31));
    linear1_3->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/3a.png);"));
    linear1_4 = new QPushButton(centralWidget);
    buttonGroup1->addButton(linear1_4);
    linear1_4->setObjectName(QStringLiteral("linear1_4"));
    linear1_4->setGeometry(QRect(50, 170, 31, 31));
    linear1_4->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/4a.png);"));
    linear1_5 = new QPushButton(centralWidget);
    buttonGroup1->addButton(linear1_5);
    linear1_5->setObjectName(QStringLiteral("linear1_5"));
    linear1_5->setGeometry(QRect(50, 320, 31, 31));
    linear1_5->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/5a.png);"));
    linear1_6 = new QPushButton(centralWidget);
    buttonGroup1->addButton(linear1_6);
    linear1_6->setObjectName(QStringLiteral("linear1_6"));
    linear1_6->setGeometry(QRect(50, 260, 31, 31));
    linear1_6->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/6a.png);"));
    linear1_7 = new QPushButton(centralWidget);
    buttonGroup1->addButton(linear1_7);
    linear1_7->setObjectName(QStringLiteral("linear1_7"));
    linear1_7->setGeometry(QRect(50, 230, 31, 31));
    linear1_7->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/7a.png);"));
    linear1_8 = new QPushButton(centralWidget);
    buttonGroup1->addButton(linear1_8);
    linear1_8->setObjectName(QStringLiteral("linear1_8"));
    linear1_8->setGeometry(QRect(50, 290, 31, 31));
    linear1_8->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/8a.png);"));
    linear1_9 = new QPushButton(centralWidget);
    buttonGroup2 = new QButtonGroup(MainWindow);
    buttonGroup2->setObjectName(QStringLiteral("buttonGroup2"));
    buttonGroup2->addButton(linear1_9);
    linear1_9->setObjectName(QStringLiteral("linear1_9"));
    linear1_9->setGeometry(QRect(580, 120, 41, 21));
    linear1_9->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/9a.png);"));
    linear1_10 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_10);
    linear1_10->setObjectName(QStringLiteral("linear1_10"));
    linear1_10->setGeometry(QRect(580, 140, 41, 21));
    linear1_10->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/10a.png);"));
    linear1_11 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_11);
    linear1_11->setObjectName(QStringLiteral("linear1_11"));
    linear1_11->setGeometry(QRect(580, 160, 41, 31));
    linear1_11->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/11a.png);"));
    linear1_12 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_12);
    linear1_12->setObjectName(QStringLiteral("linear1_12"));
    linear1_12->setGeometry(QRect(580, 190, 41, 31));
    linear1_12->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/12a.png);"));
    linear1_13 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_13);
    linear1_13->setObjectName(QStringLiteral("linear1_13"));
    linear1_13->setGeometry(QRect(580, 220, 41, 31));
    linear1_13->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/13a.png);"));
    linear1_14 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_14);
    linear1_14->setObjectName(QStringLiteral("linear1_14"));
    linear1_14->setGeometry(QRect(580, 250, 41, 31));
    linear1_14->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/14a.png);"));
    linear1_15 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_15);
    linear1_15->setObjectName(QStringLiteral("linear1_15"));
    linear1_15->setGeometry(QRect(580, 280, 41, 31));
    linear1_15->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/15a.png);"));
    linear1_16 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_16);
    linear1_16->setObjectName(QStringLiteral("linear1_16"));
    linear1_16->setGeometry(QRect(580, 310, 41, 31));
    linear1_16->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/16a.png);"));
    linear1_17 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_17);
    linear1_17->setObjectName(QStringLiteral("linear1_17"));
    linear1_17->setGeometry(QRect(580, 340, 41, 31));
    linear1_17->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/17a.png);"));
    linear1_18 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_18);
    linear1_18->setObjectName(QStringLiteral("linear1_18"));
    linear1_18->setGeometry(QRect(580, 370, 41, 31));
    linear1_18->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/18a.png);"));
    linear1_19 = new QPushButton(centralWidget);
    buttonGroup2->addButton(linear1_19);
    linear1_19->setObjectName(QStringLiteral("linear1_19"));
    linear1_19->setGeometry(QRect(580, 400, 41, 31));
    linear1_19->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/19a.png);"));
    linear1_20 = new QPushButton(centralWidget);
    buttonGroup3 = new QButtonGroup(MainWindow);
    buttonGroup3->setObjectName(QStringLiteral("buttonGroup3"));
    buttonGroup3->addButton(linear1_20);
    linear1_20->setObjectName(QStringLiteral("linear1_20"));
    linear1_20->setGeometry(QRect(140, 150, 41, 31));
    linear1_20->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/27a.png);"));
    linear1_21 = new QPushButton(centralWidget);
    buttonGroup3->addButton(linear1_21);
    linear1_21->setObjectName(QStringLiteral("linear1_21"));
    linear1_21->setGeometry(QRect(140, 180, 41, 31));
    linear1_21->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/28a.png);"));
    linear1_22 = new QPushButton(centralWidget);
    buttonGroup3->addButton(linear1_22);
    linear1_22->setObjectName(QStringLiteral("linear1_22"));
    linear1_22->setGeometry(QRect(140, 210, 41, 31));
    linear1_22->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/29a.png);"));
    linear1_23 = new QPushButton(centralWidget);
    buttonGroup3->addButton(linear1_23);
    linear1_23->setObjectName(QStringLiteral("linear1_23"));
    linear1_23->setGeometry(QRect(140, 240, 41, 31));
    linear1_23->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/30a.png);"));
    linear1_24 = new QPushButton(centralWidget);
    buttonGroup3->addButton(linear1_24);
    linear1_24->setObjectName(QStringLiteral("linear1_24"));
    linear1_24->setGeometry(QRect(140, 270, 41, 31));
    linear1_24->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/31a.png);"));
    linear1_25 = new QPushButton(centralWidget);
    buttonGroup3->addButton(linear1_25);
    linear1_25->setObjectName(QStringLiteral("linear1_25"));
    linear1_25->setGeometry(QRect(140, 300, 41, 31));
    linear1_25->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/32a.png);"));
    linear1_26 = new QPushButton(centralWidget);
    buttonGroup3->addButton(linear1_26);
    linear1_26->setObjectName(QStringLiteral("linear1_26"));
    linear1_26->setGeometry(QRect(140, 330, 41, 31));
    linear1_26->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/33a.png);"));
    linear1_27 = new QPushButton(centralWidget);
    buttonGroup3->addButton(linear1_27);
    linear1_27->setObjectName(QStringLiteral("linear1_27"));
    linear1_27->setGeometry(QRect(140, 360, 41, 31));
    linear1_27->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/34a.png);"));
    linear1_28 = new QPushButton(centralWidget);
    buttonGroup3->addButton(linear1_28);
    linear1_28->setObjectName(QStringLiteral("linear1_28"));
    linear1_28->setGeometry(QRect(140, 390, 41, 31));
    linear1_28->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/35a.png);"));
    linear1_29 = new QPushButton(centralWidget);
    buttonGroup3->addButton(linear1_29);
    linear1_29->setObjectName(QStringLiteral("linear1_29"));
    linear1_29->setGeometry(QRect(140, 420, 41, 31));
    linear1_29->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/36a.png);"));
    linear1_30 = new QPushButton(centralWidget);
    buttonGroup4 = new QButtonGroup(MainWindow);
    buttonGroup4->setObjectName(QStringLiteral("buttonGroup4"));
    buttonGroup4->addButton(linear1_30);
    linear1_30->setObjectName(QStringLiteral("linear1_30"));
    linear1_30->setGeometry(QRect(300, 190, 31, 31));
    linear1_30->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/37a.png);"));
    linear1_31 = new QPushButton(centralWidget);
    buttonGroup4->addButton(linear1_31);
    linear1_31->setObjectName(QStringLiteral("linear1_31"));
    linear1_31->setGeometry(QRect(300, 220, 31, 31));
    linear1_31->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/38a.png);"));
    linear1_32 = new QPushButton(centralWidget);
    buttonGroup4->addButton(linear1_32);
    linear1_32->setObjectName(QStringLiteral("linear1_32"));
    linear1_32->setGeometry(QRect(300, 250, 31, 31));
    linear1_32->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/39a.png);"));
    linear1_33 = new QPushButton(centralWidget);
    buttonGroup4->addButton(linear1_33);
    linear1_33->setObjectName(QStringLiteral("linear1_33"));
    linear1_33->setGeometry(QRect(300, 280, 31, 31));
    linear1_33->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/40a.png);"));
    linear1_34 = new QPushButton(centralWidget);
    buttonGroup4->addButton(linear1_34);
    linear1_34->setObjectName(QStringLiteral("linear1_34"));
    linear1_34->setGeometry(QRect(300, 310, 31, 31));
    linear1_34->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/41a.png);"));
    linear1_35 = new QPushButton(centralWidget);
    buttonGroup4->addButton(linear1_35);
    linear1_35->setObjectName(QStringLiteral("linear1_35"));
    linear1_35->setGeometry(QRect(300, 340, 31, 31));
    linear1_35->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/42a.png);"));
    linear1_36 = new QPushButton(centralWidget);
    buttonGroup4->addButton(linear1_36);
    linear1_36->setObjectName(QStringLiteral("linear1_36"));
    linear1_36->setGeometry(QRect(300, 370, 31, 31));
    linear1_36->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/43a.png);"));
    linear1_37 = new QPushButton(centralWidget);
    buttonGroup4->addButton(linear1_37);
    linear1_37->setObjectName(QStringLiteral("linear1_37"));
    linear1_37->setGeometry(QRect(300, 400, 31, 31));
    linear1_37->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/44a.png);"));
    linear1_38 = new QPushButton(centralWidget);
    buttonGroup4->addButton(linear1_38);
    linear1_38->setObjectName(QStringLiteral("linear1_38"));
    linear1_38->setGeometry(QRect(300, 430, 31, 31));
    linear1_38->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/45a.png);"));
    linear1_39 = new QPushButton(centralWidget);
    //buttonGroup4->addButton(linear1_39);
    linear1_39->setVisible(false);
    linear1_39->setObjectName(QStringLiteral("linear1_39"));
    linear1_39->setGeometry(QRect(300, 460, 31, 31));
    linear1_39->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/46a.png);"));
    linear1_40 = new QPushButton(centralWidget);
    buttonGroup5 = new QButtonGroup(MainWindow);
    buttonGroup5->setObjectName(QStringLiteral("buttonGroup5"));
    buttonGroup5->addButton(linear1_40);
    linear1_40->setObjectName(QStringLiteral("linear1_40"));
    linear1_40->setGeometry(QRect(410, 280, 31, 31));
    linear1_40->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/47a.png);"));
    linear1_41 = new QPushButton(centralWidget);
    buttonGroup5->addButton(linear1_41);
    linear1_41->setObjectName(QStringLiteral("linear1_41"));
    linear1_41->setGeometry(QRect(410, 310, 31, 31));
    linear1_41->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/48a.png);"));
    linear1_42 = new QPushButton(centralWidget);
    buttonGroup5->addButton(linear1_42);
    linear1_42->setObjectName(QStringLiteral("linear1_42"));
    linear1_42->setGeometry(QRect(410, 340, 31, 31));
    linear1_42->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/49a.png);"));
    linear1_43 = new QPushButton(centralWidget);
    buttonGroup5->addButton(linear1_43);
    linear1_43->setObjectName(QStringLiteral("linear1_43"));
    linear1_43->setGeometry(QRect(410, 370, 31, 31));
    linear1_43->setStyleSheet(QStringLiteral("border-image: url(:/new/prefix1/icon/50a.png);"));
    MainWindow->setCentralWidget(centralWidget);
    menuBar = new QMenuBar(MainWindow);
    menuBar->setObjectName(QStringLiteral("menuBar"));
    menuBar->setGeometry(QRect(0, 0, 897, 23));
    MainWindow->setMenuBar(menuBar);
    mainToolBar = new QToolBar(MainWindow);
    mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
    MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
    statusBar = new QStatusBar(MainWindow);
    statusBar->setObjectName(QStringLiteral("statusBar"));
    MainWindow->setStatusBar(statusBar);

    //子窗口区域
    area=new QMdiArea(this->centralWidget);
    //area->resize(QSize(1920,1080));//区域大小，最大化处理
    area->setGeometry(334,0,1920,1080);
    retranslateUi(MainWindow);
    QMetaObject::connectSlotsByName(MainWindow);
} // setupUi

void UI::retranslateUi(QMainWindow *MainWindow)
{
    MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
    linear1->setText(QString());
    linear1_2->setText(QString());
    linear1_3->setText(QString());
    linear1_4->setText(QString());
    linear1_5->setText(QString());
    linear1_6->setText(QString());
    linear1_7->setText(QString());
    linear1_8->setText(QString());
    linear1_9->setText(QString());
    linear1_10->setText(QString());
    linear1_11->setText(QString());
    linear1_12->setText(QString());
    linear1_13->setText(QString());
    linear1_14->setText(QString());
    linear1_15->setText(QString());
    linear1_16->setText(QString());
    linear1_17->setText(QString());
    linear1_18->setText(QString());
    linear1_19->setText(QString());
    linear1_20->setText(QString());
    linear1_21->setText(QString());
    linear1_22->setText(QString());
    linear1_23->setText(QString());
    linear1_24->setText(QString());
    linear1_25->setText(QString());
    linear1_26->setText(QString());
    linear1_27->setText(QString());
    linear1_28->setText(QString());
    linear1_29->setText(QString());
    linear1_30->setText(QString());
    linear1_31->setText(QString());
    linear1_32->setText(QString());
    linear1_33->setText(QString());
    linear1_34->setText(QString());
    linear1_35->setText(QString());
    linear1_36->setText(QString());
    linear1_37->setText(QString());
    linear1_38->setText(QString());
    linear1_39->setText(QString());
    linear1_40->setText(QString());
    linear1_41->setText(QString());
    linear1_42->setText(QString());
    linear1_43->setText(QString());
} // retranslateUi
